### ISSUE TITLE
Coefficient matrix is unlabeled

### ISSUE THREAD

**Issue by NickCH-K** [lsun20/EventStudyInteract#1]
The package seems to work great! And the documentation is clearer than `aggregate.fixest` in the R **fixest** package.

One note: the `e(b)` and `e(V)` matrices that are returned do not have the proper coefficient names for the relative-time indicators. It's there for the covariates, but not for the various `g_`s (as per the documentation). This makes it pretty tricky to pull results out to make, say, a graph after the fact.

This should be fixable with a `matrix colnames` or `matrix rownames` before the `ereturn`.

**Comment by lsun20** [comment]
Thank you very much for your interest!  I am aware of the missing labels.  I tried to label `e(b)` and `e(V)` initially but decided not to because of version difference in `reghdfe` that may or may not report the constant.  Instead, I extract the relevant estimates in `e(b_interact)` and just updated the code to extract `e(V_interact)` as well.  Sorry about the confusion from the documentation!  The documentation is updated, also with an example of `coefplot`.
